---
stats:
  sar:
    monitor:
      - memory
      - cpu
      - paging
      - TCP
      - UDP
      - switch
  influx:
    connection:
      host: influxdb
      port: 8086
      user: root
      password: root
      dbname: test
    parameters:
      grouptime: 10s
  bpf:
    monitor:
      - cachestat
      - cpudist
      - tcplife
      - vfsreadlat
      - recvlat
  perf: 
    monitor:
      - QC-TASK-RUNNER
      - QC-CHECK-RUNNER
test:
  delay: 30s
  duration: 15m
  command: qcRunBenchmark 
  config:
    monitoring: influxdb-udp://influxdb:8088/debug
    #    monitoring: infologger:///debug?qc
  parameters:
    size:
      - 1000
      - 1000000
    frequency:
      - 1000000
      - 1000
      - 1
    task_time:
      - 1000
      - 10000
    check_time:
      - 1000
      - 1000000

